---
title: "Computational methods in landscape ecology"

author:
  - name: Maximilian H.K. Hesselbarth
    affil-id: 1
  - name: Jakub Nowosad
    affil-id: 2,3
  - name: Alida de Flamingh
    affil-id: 4
  - name: Craig E. Simpkins
    affil-id: 5
  - name: Martin Jung
    affil-id: 1
  - name: Gemma Gerber
    affil-id: 1
  - name: Martí Bosch
    affil-id: 6

affiliations:
  - id: 1
    name: International Institute for Applied Systems Analysis, Biodiversity, Ecology, and Conservation Group, Laxenburg, Austria
  - id: 2
    name: Adam Mickiewicz University, Poznań, Poland
  - id: 3
    name: University of Münster, Münster, Germany
  - id: 4
    name: Carl R. Woese Institute for Genomic Biology, University of Illinois at Urbana-Champaign, Urbana, IL, USA 
  - id: 5
    name: Auckland Council, Environmental Services, Auckland, New Zealand
  - id: 6
    name: École polytechnique fédérale de Lausanne, Lausanne, Switzerland

format:
  pdf:
    template-partials:
      - title.tex
    include-in-header:
      text: |
        \usepackage{academicons}
        \usepackage{fontawesome5}
        \usepackage{lineno}\linenumbers
        \usepackage[noblocks]{authblk}
        \usepackage{setspace}
        \renewcommand\Affilfont{\footnotesize}
        \newcommand{\orcid}[1]{\href{https://orcid.org/#1}{\textcolor[HTML]{A6CE39}{\aiOrcid\hspace{1mm}#1}}}
        \newcommand{\mail}[1]{\href{mailto:#1}{\textcolor[HTML]{052E81}{\faEnvelope\hspace{1mm}#1}}}

papersize: a4paper
fontsize: 11pt
geometry: margin=25mm
indent: 2m
linestretch: 1.5
number-sections: false

bibliography: CLER.bib
csl: springer-basic-brackets-no-et-al.csl
---

\noindent \footnotesize M.H.K. Hesselbarth \orcid{0000-0003-1125-9918} \hspace{5mm} \mail{mhk.hesselbarth@gmail.com}

\noindent \footnotesize J. Nowosad \orcid{0000-0002-1057-3721}

\noindent \footnotesize A. de Flamingh \orcid{0000-0003-1223-6654}

\noindent \footnotesize C.E. Simpkins \orcid{0000-0003-3212-1379}

\noindent \footnotesize M. Jung \orcid{0000-0002-7569-1390}

\noindent \footnotesize G. Gerber \orcid{0000-0002-8722-3113}

\noindent \footnotesize M. Bosch \orcid{0000-0001-8735-9144}

\noindent \small \textit{Keywords: (1) spatial data, (2) spatial patterns, (3) pattern-process link (4) open-source, (5) scientific software}

\noindent \textbf{Acknowledgments}

\noindent We are thankful to the anonymous reviewers and the editors who provided valuable comments to improve the manuscript.

\noindent \textbf{Funding}

\noindent No external funding was received.

\noindent \textbf{Author contributions}

\noindent All authors contributed particular sections to the manuscript and assisted with the revision. sOverall coordination, first and revised draft was led by MHKH.
Correspondence to [mhk.hesselbarth@gmail.com](mailto:mhk.hesselbarth@gmail.com)

\noindent \textbf{Conflict of Interest}

\noindent The authors declare no competing interests.

\noindent \textbf{Human and Animal Rights and Informed Consent}

\noindent This article does not contain any studies with human or animal subjects performed by any of the authors.

# Abstract

## Purpose of Review

Landscapes can be defined as mosaics of different land covers, habitats, ecosystems, or land-use systems.
The link between spatial heterogeneous patterns and ecological processes is the core concept in the research field of landscape ecology.
Nowadays, advanced computational methods are essential to the field due to its cross-disciplinary nature, the increasing availability of data, and the complexity of landscape systems.

## Recent findings

This review provides an overview of recent developments in computational methods that have advanced the research field of landscape ecology.
We focus on key topics such as spatial patterns, connectivity, simulations and modeling, landscape genetics, and spatial planning.

## Summary

The review highlights key innovations, challenges, and potential future directions in the field, emphasizing the role of computational methods in addressing complex ecological questions.

<!-- R1: Figure 1. The links between Spatial sampling, Spatial planning, and Genetics, towards Landscape mean? The figure would be more meaningful with an explanation of these links, either in the caption or directly on the figure. Also, for other topics (e.g. connectivity), a keyword (or short sentence) summarizing the contribution of the topic to Landscape Ecology would be great. -->

{{< include Sections/01-introduction.qmd >}}
{{< include Sections/02-data.qmd >}}
{{< include Sections/03-spatial-patterns.qmd >}}
{{< include Sections/04-connectivity.qmd >}}
{{< include Sections/05-sampling.qmd >}}
{{< include Sections/06-simulations.qmd >}}
{{< include Sections/07-genetics.qmd >}}
{{< include Sections/08-spatial-planning.qmd >}}
{{< include Sections/09-conclusion.qmd >}}

# Key references

\noindent _Frazier (2019) Emerging trajectories for spatial pattern analysis in landscape ecology. Landscape Ecology 34:2073–2082._ The paper describes how interdisciplinary perspectives have contributed to spatial pattern analysis and introduces new innovative developments.

\noindent _Unnithan Kumar et al. (2022) Moving beyond landscape resistance: Considerations for the future of connectivity modeling and conservation science. Landscape Ecology 37:2465–2480._ The paper provides a historical overview of connectivity modeling with a focus on resistance surfaces and discusses current missing aspects and how to address them.  

\noindent _Zuckerberg et al. (2020) A review of overlapping landscapes: Pseudoreplication or a red herring in landscape ecology? Current Landscape Ecology Reports 5:140–148._ The paper discusses theoretical and practical implications over overlapping landscapes in the context of landscape buffers of varying sizes surrounding sampling sites.

\noindent _Synes et al. (2016) Emerging opportunities for landscape ecological modeling. Current Landscape Ecology Reports 1:146–167._ The paper identifies existing gaps in landscape ecological modeling while highlighting potential emerging opportunities.

\noindent _Manel and Holderegger (2013) Ten years of landscape genetics. Trends in Ecology & Evolution 28:614–621._ Ten years after their first paper introducing landscape genetics, this paper reviews the state-of-the-art and describes main topics that have contributed to the progress of landscape genetics.

\noindent _Jung et al. (2024) An assessment of the state of conservation planning in europe. Philosophical Transactions of the Royal Society B 379:20230015._ The paper assesses where and how spatial conservation planning have been applied across Europe. 

# References

\footnotesize
\setstretch{1.0}
::: {#refs}
:::
