---
bibliography: CLER.bib
---

<!-- Person responsible: Hesselbarth, Nowosad -->

# Data models {#sec-data}

<!-- The choice of the data type, model, and scale are crucial for the analysis's results because every type is a simplified model of the natural world. -->

There are two fundamental data models used to represents landscapes, namely the raster and the vector data model. 
The raster data model typically uses regularly spaced grid cells, while the vector data model uses points, lines, and polygons to represent landscape features [@With2019EssentialsLandscape].
Often, the choice of the data model is driven by data and software availability or by familiarity with the approach [@Costanza2019DescribingAnalyzing].
For example, many LULC maps are provided as gridded raster data as they often relate to underlying remote sensing products.

Similarly the issue of scale is closely related to the used data model. 
This includes the extent of the study area and resolution of the data (i.e., the smallest data unit).
Additionally, thematic resolution in landscape ecology often refers to the values describing landscape features, e.g., the number of discrete LULC categories or habitats
[@Jung2020GlobalMap].
Various classification systems are relevant at local, regional, and global extent, such as the National Land Cover Database (NLCD), the Coordination of Information on the Environment (CORINE), or the Food and Agriculture Organization (FAO) systems [@Nedd2021SynthesisLand].
Lastly, temporal scales are relevant in terms of extent and resolution, but also with regards to the detail of captured ecological processes.

The spatial reference system of the data is less frequently discussed but often critical. 
Cartesian coordinate reference systems measure distances between two points in Euclidean distances, typically in meters. 
In contrast, geographic coordinate reference systems are based on degrees and measure distances as great-circle distances.
Numerous coordinate reference systems exist and novel projections are constantly being developed to improve spatial cohesion, efficiency and accuracy [@Bauer-Marschallinger2014OptimisationGlobal].
However each reference systems comes with distinct properties that may distort areas, distances, angles, and aimed to represent specific regions or countries. 
Therefore, it is essential to choose the appropriate spatial reference system based on the available data, area of interest, and the specific research question.

Data quality is generally variable, and data products are not flawless, potentially containing errors and biases.
For example, global land-cover products typically have an overall accuracy of 70 to 80% [@Xu2024ComparativeValidation], indicating that 20 to 30% of the grid cells may be misclassified.
Furthermore, these misclassifications are not random, but are often correlated with specific LULC types, regions, and seasonal variations [@Liu2021FinerresolutionMapping]. 
Rather than relying on global products, however, there are also increasingly voices that advocate for the production and use of regional land-cover products [@Tulbure2022RegionalMatters].
Nevertheless, many landscape ecology studies tend to accept the data at face value, neglecting its accuracy and inherent uncertainty. 