---
bibliography: CLER.bib
---

<!-- Person responsible: Jung -->

# Spatial conservation planning {#sec-spatialplanning}

Spatial planning broadly considers the use of decision theory to identify and allocate areas to specific purposes, such as reserve selection through spatial conservation prioritization approaches [@margules2000systematic; @kukkala2013core; @jung2024assessment]. In the context of landscape-ecology it provides the critical link between the measuring of patterns and processes (see section @sec-spatialpattern), and outcomes related to actual decision making by distinguishing between structure, function and scales [@hersperger2021landscape]. Although - as integrative approach - most spatial planning approaches can benefit from other computational advances in landscape ecology, such as for example through using simulation model outputs (see section @sec-simulation) as input features to the planning (see also @daigle2020operationalizing), there have also been several recent frontiers in directly considering landscape patterns directly in spatial planning.

Spatial patterns in terms of shape and patterns have always been of interest to spatial planning. Generally, such patterns influence planning outcomes because of their spatial *compactness*, *contiguity* and *connectedness*. Aggregation can be important because of ecological reasoning or practical feasibility, for example by ensuring that any selected areas satisfy certain minimum patch size constraints [@smith2010approach;@justeau2021constrained]. Novel computational approaches make use of graph theory to identify those areas in a landscape more likely to be of values as compact core habitat and reducing boundary exposure [@weerasena2023sequential]. Similarly contiguity and connectivity are often seen as important to ensure that landscapes and patches of specific characteristics are connected, such as for example river networks [@beger2010incorporating]. In particular the direct consideration of connectivity in spatial conservation planning has received much recent attention and computational methods are increasingly developed [@hanson2019conventional; @daigle2020operationalizing; @hanson2022comparison; @beger2022demystifying].

Particular noteworthy here are two advances in incorporating landscape indices in spatial planning. One is the use of graph theory in linear programming to guide conservation and restoration efforts [@justeau2021constrained; @hamonic2023cumulative]. For example, in a New Caledonia case study @justeau2021constrained showed how theory and indicators from landscape ecology to determine where restoration efforts would best be located to maximize broader landscape connectivity. The direct consideration of graph theoretic approaches in spatial networks has the potential to be provide more cost-effective and precise solutions to the design of reserve networks [@hamonic2023cumulative].

A second main advance is the increasing use of deep reinforcement learning (RL), a machine learning approach based not on patterns but agents and pathway, in spatial planning. RL can be used to identify cost-efficient solutions to area-based conservation planning [@silvestro2022improving] or typical connectivity problems [@equihua2024connectivity], where the objective is to identify best possible improvements to landscape connectivity indices such as the Integral Index of Connectivity. Advantages of RL are that they are able to easier incorporate linear and non-linear functions and spatial-temporal processes in the planning and are generally more readibly scalable to larger spatial extent [@equihua2024connectivity], which however comes with the downside of decreasing interpretability.

## Open-source software in spatial conservation planning {#sec-spatialplanning-software}

Multiple open-source software solutions have been developed to support further integration of landscape ecology theory and indicators into spatial planning. Most of these software are based on linear or constrained programming approaches, which however require a solver to create any outputs. Unfortunately there is still a gap between state-of-the art open-source and proprietary solvers in terms of computational efficiency [@hanson2019optimality].

Noteworthy software is the *prioritizr* R-package [@hanson2024prioritizr] which supports a range of compactness and contiguity constraints and penalties, and generally allows for the flexibly creation of planning problems in multiple configurations. 
Similarly, the *coco* package makes use of connectivity constraints in an integer linear planning framework to identify potential outcomes that minimize further fragmentation of landscapes [@van2023coco]. The new *restoptr* R-package makes use of constrained programming for those areas to be restored in a region that would most effectively contribute to greater landscape connectivity [@justeau2023restoptr]. Innovatively, it uses landscape ecology indices not as constraints, but as specific targets (e.g. where one could best maximize the effective mesh size in a region). The *CAPTAIN* software suite enables the application of reinforcement learning for area-based conservation efforts [@silvestro2022improving].
Overall, most of these software however still require substantial prior knowledge on (spatial) optimization and statistics, which can be an entry barrier to more widespread uptake.
