---
bibliography: CLER.bib
---

<!-- Person responsible: Hesselbarth -->

# Discussion {#sec-disc}

Since it emerged in the 1980s [@With2019EssentialsLandscape], the research field of landscape ecology has constantly evolved and is now highly depending on computational methods.
Thus, future progress within the field will largely depend on available software and analysis tools [@Costanza2019DescribingAnalyzing].
Here, we present and summarize some recent developments of computational methods related to spatial patterns, connectivity, simulations and modelling, landscape genetics and spatial planning.
In this context, we highlight open-source software as a cornerstone of "Open Science" which offers key advantages like shareability, reproducibility, and transparency, providing great benefits to the research community [@Powers2019OpenScience; @Vogt2019PatternsSoftware].

Alongside the previously introduced methodological advances specific to landscape ecology, the research field will also benefit from technological innovations from related disciplines.
<!-- JN: what are "large satellites"?  -->
This includes advances in remote sensing technology, with increasing data availability and diversity from a range of sources, including large satellites, unmanned aerial vehicles, and ground-based sensor systems.
These systems provide both passive sensors such as multispectral, hyperspectral, and thermal sensors, and active optical sensors such as LiDAR and SAR [@Crowley2020RemoteSensings].
Related to this, there is a growing number of up- and downscaling approaches for remote sensing data which makes a wider range of products accessible for research studies [@Markham2023ReviewMethods].
<!-- JN: "is entering" or "has entered"? -->
In combination with other increasingly available data sources, e.g, citizen science data, ecology is entering the era of big data, requiring methods that can handle heterogeneous data and high-throughput computing resources [@Farley2018SituatingEcology].
Due to its high flexibility and performance, artificial intelligence has become popular in ecology and deep learning and machine learning algorithms can be used for e.g., mapping, classification and feature extraction, modelling, or predicting [@Christin2019ApplicationsDeep; @Stupariu2022MachineLearning; @Pichler2023MachineLearning].
Furthermore, quantum computing may additionally offer a potential pathway to surpass the limits of current computational technologies [@Woolnough2023QuantumComputing].
Last, landscape ecology will, as many other research fields, benefit from a general paradigm shift related to data sharing, management, and documentation [@Tenopir2020DataSharing].

Climate change as well as the biodiversity crisis are two intervened and complex issues that need integrative, multi-disciplinary, and scale-dependent solutions to face them [@Pettorelli2021TimeIntegrate; @Portner2023OvercomingCoupled].
Landscape ecology is well equipped to provide answers because it connects several research fields at multiple scales, such as social sciences, geography, and ecology and evolution [@With2019EssentialsLandscape].
Up-to-date and constantly evolving computational methods are required to meet the increasing complexity of research questions.
Nevertheless, the here provided review of the latest computational methods in landscape ecology can only be a snapshot in time because new approaches will emerge in the future.
