---
bibliography: CLER.bib
---

<!-- Person responsible: Hesselbarth, Nowosad, Bosch, Jung  -->

# Software and programming languages

"Open science" involves full transparency and data access at all stages of the research processes and integrative and multi-disciplinary fields such as ecology can massively benefit from this concept [@Hampton2015TaoOpen].
Using open source software is one key aspect of open science because it ensures transparency and consequently increases trust in the analyses [@Powers2019OpenScience].
Given the increasing data availability and method complexity, future progress within the research field will highly depend on available software and analysis tools [@Costanza2019DescribingAnalyzing].
In this context, script-based workflows have an advantage over workflows involving graphical user interfaces because the former are more shareable and reproducible [@Hampton2015TaoOpen; @Powers2019OpenScience].
Thus, we will focus the following section on script-based open-source software suitable for landscape ecology.

<!-- R: Hesselbarth -->
The open-source, script-based R programming languages [@RCoreTeam2024LanguageEnvironment] was first released in 1995 [@Smith201616Years] with a focus on statistical computing and data visualization.
However, due to its extensions (also called packages), the language is popular in many academic fields, including ecology [@Lai2019EvaluatingPopularity; @Lortie2020ChecklistChoosing], and it is suitable for spatial data analysis and landscape ecology [e.g., @Bivand2020ProgressEcosystem; @Hesselbarth2021OpensourceTools].
Fundamental packages for spatial data analysis include *sf* for simple-features vector data [@Pebesma2018SimpleFeatures], *terra* for raster data [@Hijmans2024TerraSpatial], *stars* for spatiotemporal arrays, raster, and vector data cubes [@Pebesma2023SpatialData], and *spatstat* for point pattern data [@Baddeley2015SpatialPoint].
Several packages allow to create maps, such as *tmap* [@Tennekes2018TmapThematic] or *ggplot2* [@Wickham2016Ggplot2Elegant]. 
For a comprehensive overview of packages related to geographical spatial data, please see the CRAN Task View [@Bivand2024CRANTask].
R packages developed specifically for spatial pattern analysis include, besides others, *landscapemetrics* [@Hesselbarth2019LandscapemetricsOpen], *vectormetrics* [still being developed; @Matuszek2024VectormetricsLandscape], *motif* [@Nowosad2021MotifOpensource], *rasterdiv* [@Rocchini2021RasterdivInformation], or *geodiv* [@Smith2021GeodivPackage]. 
<!-- BESSpatial: https://github.com/Nowosad/bespatial/ -->
Packages with a focus on scale include e.g., *multilandr* [@Huais2024MultilandrPackage] or *grainchanger* [@Graham2024GrainchangerMovingwindow].
Connectivity analysis can be conducted using packages including *lconnect* [@Mestre2023LconnectPackage], or *grainscape* [@Chubaty2020ToolboxGrainscape].
Furthermore, neutral landscapes can be simulated using *NLMR* [@Sciaini2018NLMRLandscapetools], and the *graph4lg* [@Savary2021Graph4lgPackage] provides functions for landscape genetics.

<!-- Python: Bosch, Jung? -->