---
bibliography: CLER.bib
---

<!-- Person responsible: Hesselbarth -->

# Conclusion {#sec-disc}

Since its emergence in the 1980s [@With2019EssentialsLandscape], landscape ecology research has constantly evolved and is now highly dependent on computational methods.
Thus, future progress within the field will largely depend on integration of novel data sources and available software and computational tools [@Costanza2019DescribingAnalyzing].
Here, we present and summarize some recent developments of computational methods related to spatial patterns, connectivity, simulations and modeling, landscape genetics and spatial planning.
In this context, we highlight open-source software as a cornerstone of "Open Science" offering key advantages like shareability, reproducibility, and transparency, which provide great benefits to the research community [@Powers2019OpenScience; @Vogt2019PatternsSoftware].

\newpage
\setstretch{1.0}

| Topic | Programming language | Software | Reference |
|:---:|:---:|:---:|:---:|
| Spatial patterns | R | sf | [@Pebesma2018SimpleFeatures] |
| Spatial patterns | R | terra | [@Hijmans2024TerraSpatial] |
| Spatial patterns | R | landscapemetrics | [@Hesselbarth2019LandscapemetricsOpensource] |
| Spatial patterns | R | multilandr | [@Huais2024MultilandrPackage] |
| Spatial patterns | R | bespatial | [@Nowosad2024BespatialBoltzmann] |
| Spatial patterns | R | rasterdiv | [@Rocchini2021RasterdivInformation] |
| Spatial patterns | R | LandComp | [@Konrad2023AdaptingMultiscale] |
| Spatial patterns | R | geodiv | [@Smith2021GeodivPackage] |
| Spatial patterns | R | glcm | [@Zvoleff2020GlcmCalculate] |
| Spatial patterns | R | vectormetrics | [@Matuszek2024VectormetricsLandscape] |
| Spatial patterns | R | motif | [@Nowosad2021MotifOpensource] |
| Spatial patterns | Python | GeoPandas | [@Jordahl2020GeopandasPython] |
| Spatial patterns | Python | Rasterio | [@Gillies2013RasterioGeospatial] |
| Spatial patterns | Python | PyLandStats | [@Bosch2019PyLandStatsOpensource] |
| Spatial patterns | Python | LecoS | [@Jung2016LecoSPython] |
| Spatial patterns | Julia | GeoStats | [@Hoffimann2018GeoStatsjlHighperformance] |
| Spatial patterns | Julia | GeoInterface | [@JuliaGeoandcontributors2024GeoInterfaceJulia] |
| Spatial patterns | Stand-alone software | FRAGSTATS | [@McGarigal2023FRAGSTATSV4] |
| Spatial patterns | Stand-alone software | GuidosToolbox | [@Vogt2017GuidosToolboxUniversal] |
| Connectivity | R | ResistanceGA | [@Peterman2018ResistanceGAPackage] |
| Connectivity | R | lconnect | [@Mestre2023LconnectPackage] |
| Connectivity | R | grainscape | [@Chubaty2020ToolboxGrainscape] |
| Connectivity | Julia | Circuitscape | [@Anantharaman2019CircuitscapeJulia] |
| Connectivity | Julia | ConScape | [@vanMoorter2023AcceleratingAdvances] |
| Connectivity | Julia | Omniscape | [@Landau2021OmniscapejlSoftware] |
| Connectivity | Stand-alone software | Graphab | [@Foltete2012SoftwareTool] |
| Connectivity | Stand-alone software | Conefor | [@Saura2009ConeforSensinode] |
| Connectivity | Stand-alone software | LSCorridors | [@Ribeiro2017LandScapeCorridors] |
| Landscape genetics | R | graph4lg | [@Savary2021Graph4lgPackage] |
| Landscape genetics | R | landgenreport | [@Gruber2015LandgenreportNew] |
| Landscape genetics | R | adegenet | [@Jombart2008AdegenetPackage] |
| Landscape genetics | R | ape | [@Paradis2019Ape50] |
| Landscape genetics | Python | Python based scripts | [@Etherington2011PythonBased] |
| Landscape genetics | Python | SDMtoolbox 2.0 | [@Brown2017SDMtoolbox20] |
| Sampling | Python | ZonalMetrics | [@Adamczyk2017ZonalMetricsPython] |
| Simulation models | R | NLMR | [@Sciaini2018NLMRLandscapetools] |
| Simulation models | R | rflsgen | [@Justeau-Allaire2022FragmentedLandscape] |
| Simulation models | Python | NLMpy | [@Etherington2015NLMpyPython] |
| Simulation models | Python | Pathwalker | [@UnnithanKumar2022PathwalkerNew] |
| Simulation models | Julia | NeutralLandscapes | [@Poisot2023NeutralLandscapesJulia] |
| Simulation models | Stand-alone software | GradientLand | [@Cambui2015GradientLandSoftware] |
| Simulation models | Stand-alone software | Landscape Generator | [@vanStrien2016ImprovedNeutral] |
| Simulation models | Stand-alone software | HexSim | [@Schumaker2018HexSimModeling] |
| Simulation models | Stand-alone software | RangeShifter2.0 | [@Bocedi2021RangeShifter20] |
| Spatial planning | R | prioritizr | [@Hanson2024PrioritizrSystematic] |
| Spatial planning | R | CoCo | [@vanMantgem2023CocoConservation] |
| Spatial planning | R | restoptr | [@Justeau-Allaire2023RestoptrPackage] |
| Spatial planning | Python | CAPTAIN | [@Silvestro2022ImprovingBiodiversity] |

: Software and models that implement recent methodological advances in landscape ecology.

\newpage
\normalsize
\setstretch{1.5}

Alongside the previously introduced methodological advances specific to landscape ecology, the research field will also benefit from technological innovations from related disciplines.
This includes advances in remote sensing technology with increasing data availability and diversity from a range of sources, including satellites, unmanned aerial vehicles, and ground-based sensor systems [@Yu2019LandscapeEcology; @Crowley2020RemoteSensings].
These systems provide both passive sensors, such as multispectral, hyperspectral, and thermal sensors and active optical sensors, such as LiDAR and SAR [@Crowley2020RemoteSensings].
Related to this, there is a growing number of up- and downscaling approaches for remote sensing data which makes a wider range of products accessible [@Markham2023ReviewMethods].
In combination with other increasingly available data sources, e.g, citizen science data, ecology has entered the era of big data, requiring methods that can handle heterogeneous data and high-throughput computing resources [@Farley2018SituatingEcology].
Due to its high flexibility and performance artificial intelligence has become popular in ecology, and deep learning and machine learning algorithms can be used for, e.g., mapping, classifying and extracting features, modeling, or predicting [@Christin2019ApplicationsDeep; @Stupariu2022MachineLearning; @Pichler2023MachineLearning].
Furthermore, quantum computing may additionally offer a potential pathway to surpass the limits of current computational technologies [@Woolnough2023QuantumComputing].
Last, landscape ecology will, as many other research fields, benefit from a general paradigm shift related to data sharing, management, and documentation [@Tenopir2020DataSharing].

Climate change, as well as the biodiversity crisis, are two intervening and complex issues that need integrative, multi-disciplinary, and scale-dependent solutions to face them [@Pettorelli2021TimeIntegrate; @Portner2023OvercomingCoupled].
Landscape ecology is well equipped to provide answers because it connects several research fields at multiple scales, such as social sciences, geography, and ecology and evolution [@With2019EssentialsLandscape].
Up-to-date and constantly evolving computational methods are required to meet the increasing complexity of research questions.
Nevertheless, the review provided here that showcases current computational methods in landscape ecology will only be a snapshot in time because of the development and emergence of future analytical approaches.
