---
bibliography: CLER.bib
---

<!-- Person responsible: Hesselbarth -->

# Introduction

Landscapes are typically defined as mosaics of different land covers, habitats, ecosystems, or land use systems [@Forman1986; @Forman1995] - with empathize on heterogeneity of at least one factor of interest [@Turner2015].
Linking the spatial heterogeneity and ecological processes, including potential feedbacks, is the fundamental concept of landscape ecology [@Risser1984; @Turner1989; @Turner2005].
Typical research topics include ecological flows in landscape mosaics, drivers and consequences of land use and land cover change, nonlinear dynamics and landscape complexity, scale and scaling, spatial analysis and landscape modeling, linking landscape metrics to ecological processes, integrating humans and their activities into landscape ecology, landscape conservation and sustainability, or accuracy assessment and uncertainty analysis [@Wu2002; @Wu2013].

<!-- MH: Currently using "computational science", "computational ecology", and "computational methods". Streamline terms?--> 
Computational science involves analyzing abstracted core mechanisms of research questions using data and algorithms.
Thus, computational ecology can be defined as computational science that is used to address ecological research questions with focus on complex, adaptive systems and data-driven approaches [@Poisot2019].
Computational ecology in general and simulations specifically are of importance for ecology because ecological data is often context- and scale-dependent and unfeasible to study in reproducible, replicable, and controllable experimental settings [@Petrovskii2012; but see @Wiersma2022]. Because landscape ecology is a cross-disciplinary field including, e.g., social sciences, geography, or ecology and evolution [@Wiens1997; @With2019], the general increase of available data [@Chi2016; @Jaric2020; @Nathan2022; @Wuest2020], or the complex landscape systems [@Newman2019], there is the need for sophisticated computational methods in order to link patterns and processes. Thus, computational methods are one of the most important tools of modern scientific research [@Prlic2012; @Wilson2014].

This paper aims to introduce the latest developments of computation methods in landscape ecology.
However, it is neither a systematic review of the literature nor general introduction to (computational) landscape ecology.
For a more comprehensive introductions to landscape ecology in general, please see Turner and Gardner [-@Turner2015] or Gergel and Turner [-@Gergel2017].
